/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio1_interfaces;

/**
 *
 * @author Alumno
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    GenerarLibros generarLibros = new GenerarLibros();
    public GUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTN_Aceptar = new javax.swing.JButton();
        BTN_Cancelar = new javax.swing.JButton();
        LBL_TipoFichero = new javax.swing.JLabel();
        CMB_TipoFichero = new javax.swing.JComboBox<>();
        LBL_Titulo = new javax.swing.JLabel();
        LBL_Categoria = new javax.swing.JLabel();
        LBL_Autor = new javax.swing.JLabel();
        TXT_Titulo = new javax.swing.JTextField();
        TXT_Categoria = new javax.swing.JTextField();
        TXT_Autor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TXT_NumLibros = new javax.swing.JTextField();
        CMB_NumLibros = new javax.swing.JComboBox<>();
        BTN_NumLibros_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTN_Aceptar.setText("Aceptar");
        BTN_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AceptarActionPerformed(evt);
            }
        });

        BTN_Cancelar.setText("Cancelar");
        BTN_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CancelarActionPerformed(evt);
            }
        });

        LBL_TipoFichero.setText("Tipo de fichero:");

        CMB_TipoFichero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Text", "XML" }));
        CMB_TipoFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMB_TipoFicheroActionPerformed(evt);
            }
        });

        LBL_Titulo.setText("Titulo:");

        LBL_Categoria.setText("Categoria:");

        LBL_Autor.setText("Autor:");

        jLabel1.setText("Numero Libros:");

        TXT_NumLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_NumLibrosActionPerformed(evt);
            }
        });

        CMB_NumLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMB_NumLibrosActionPerformed(evt);
            }
        });

        BTN_NumLibros_ok.setText("ok");
        BTN_NumLibros_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_NumLibros_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBL_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBL_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LBL_TipoFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CMB_TipoFichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTN_Cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TXT_Titulo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TXT_Categoria)
                    .addComponent(TXT_Autor)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXT_NumLibros, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_NumLibros_ok)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CMB_NumLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_TipoFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMB_TipoFichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(TXT_NumLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_NumLibros_ok))
                .addGap(18, 18, 18)
                .addComponent(CMB_NumLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXT_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBL_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CMB_TipoFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMB_TipoFicheroActionPerformed
        String type = CMB_TipoFichero.getSelectedItem().toString().toLowerCase();
        switch(type){
            case "xml":
                generarLibros.type = ".xml";
                break;
            case "text":
                generarLibros.type = ".txt";
                break;
            default:
                generarLibros.type = ".txt";
        }
    }//GEN-LAST:event_CMB_TipoFicheroActionPerformed

    private void BTN_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AceptarActionPerformed
        generarLibros.titulo_libro = TXT_Titulo.getText();
        generarLibros.autor_libro = TXT_Autor.getText();
        generarLibros.categoria_libro = TXT_Categoria.getText();
        generarLibros.generarArchivo();
    }//GEN-LAST:event_BTN_AceptarActionPerformed

    private void BTN_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BTN_CancelarActionPerformed

    private void TXT_NumLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_NumLibrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_NumLibrosActionPerformed

    private void BTN_NumLibros_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NumLibros_okActionPerformed
       int numLibros = Integer.parseInt(TXT_NumLibros.getText());
        for (int i = 0; i < numLibros; i++) {
            CMB_NumLibros.addItem("Libro "+(i+1));
        }
    }//GEN-LAST:event_BTN_NumLibros_okActionPerformed

    private void CMB_NumLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMB_NumLibrosActionPerformed
       TXT_Titulo.setText("");
       TXT_Autor.setText("");
       TXT_Categoria.setText("");
    }//GEN-LAST:event_CMB_NumLibrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Aceptar;
    private javax.swing.JButton BTN_Cancelar;
    private javax.swing.JButton BTN_NumLibros_ok;
    private javax.swing.JComboBox<String> CMB_NumLibros;
    private javax.swing.JComboBox<String> CMB_TipoFichero;
    private javax.swing.JLabel LBL_Autor;
    private javax.swing.JLabel LBL_Categoria;
    private javax.swing.JLabel LBL_TipoFichero;
    private javax.swing.JLabel LBL_Titulo;
    private javax.swing.JTextField TXT_Autor;
    private javax.swing.JTextField TXT_Categoria;
    private javax.swing.JTextField TXT_NumLibros;
    private javax.swing.JTextField TXT_Titulo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
